version: '3.8'

services:
  app:
    build: .
    container_name: submission-service
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - submission-network

  postgres:
    image: postgres:13
    container_name: submission-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=submissions
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - submission-network

  redis:
    image: redis:6-alpine
    container_name: submission-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - submission-network


  alembic:
    build: .
    container_name: submission-alembic
    depends_on:
      - postgres
    command: alembic upgrade head
    env_file:
      - .env
    networks:
      - submission-network

volumes:
  postgres-data:
  redis-data:

networks:
  submission-network:
    driver: bridge